### ISSUE TITLE
Analytics and event tracking

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#198]
- [ ] Set up a Google Analytics property and make sure TCC team have access (should we set it up in _their_ Google Analytics organisation?)
- [ ] Add cookie-less GA4 tracking script to the site (use CAPE as an example)
- [ ] Generate GA4 events when:
   - homepage area/MP search form submitted
   - homepage geolocation link clicked
   - explore page "add data to filter by" button clicked
   - explore page filter added (bonus points if we can record the dataset name, to track popularity of datasets over time)
   - explore page "add dataset to shade results" button clicked
   - explore page shader added (again, bonus if we can record dataset name)
   - explore page map, or table, or CSV rendered
   - explore page map constituency clicked
- [x] Update [privacy policy](https://github.com/mysociety/local-intelligence-hub/issues/69) to acknowledge cookie-less Google Analytics tracking
