### ISSUE TITLE
Prepare for public release

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#378]
This is mostly a merging and rebasing task which I think needs to happen in this order:

- [x] finish new area page PR [#349] and merge to main
- [x] finish PPC PR [#372] and merge to multiple geometry staging
- [x] rebase multiple geometry staging on main (and update area page changed here to use above
- [x] update new constituency conversion PR [#365] for recent imports and merge

Staging site:

- [x] set up a staging site as live.

Need to check that CSS caching etc is working correctly too:
- [x] cache headers
- [x] css cache/uuid things
- [x] js cache
- [x] images?
- [x] compressing js/css
- [x] gzip

**Comment by struan** [comment]
Public release done
